### ISSUE TITLE
I often click "Done" when I want to select something just below it.

### ISSUE THREAD

**Issue by cmatsuo** [movabletype/smartphone-app#132]
look at attached image. 
I often click "Done" and end up just go back to previous screen instead of could select "Plane Text", and it's really annoying. And this isn't only one, some similar screens exist.

I'm not sure how the UI should be like but any better UI idea? 

![done](https://cloud.githubusercontent.com/assets/546386/10478603/b100871a-7299-11e5-8a3b-fa1b66aeebb0.png)

**Comment by takkyun** [comment]
Hitting area of "Done" (完了) is bigger than visual. Several way to solve:

- putting section header
- getting rid of "Done" button from Navigation bar (like usual iOS interaction, as soon as user selects option, it's immediately applied (as a result, no confirmation dialog will be shown)
- making tick mark into left.  The reason why user may try to tap right side is that tick mark is shown right side, then he/she thinks to select an option may need to tap right side.  Actually row itself is selectable, so it's not necessary to tap right side of row.  Bring tick mark into left may help such confusion, however personally I don't recommend because it feels unusual interface for iOS.
- making "Done" button's hit area smaller.  I think it's some way to reduce it's hit area (actually I did in the past, although I can't remember how I did ... sorry)
- any other?

===

"Done (完了)" ボタンの判定範囲が表示よりやや広めなので起こる現象だと思います。対応策はいくつかあると思います。

- セクションヘッダーをつける。その分、row が下がるので、選択しやすくなります。
- 設定と同じように、完了ボタンをナビゲーションバーからなくす。アイテムを選択した段階で設定として反映させる。iOS の標準の動作に近くなると思います。戻るボタンを押した際の保存しますかの確認は実質表示されなくなります。
- チェックマークを左側に置く。右側にあるので、右側をタップしなくちゃと思う可能性があるのかもしれません。左側におけば、勘違いされにくい？でも、根本的な解決にはなりませんし、iOS の標準的な UI とも少し離れます。
- ナビゲーションバーの完了ボタンの判定範囲を狭くする。以前同じような問題に対処したとき、判定範囲を実質ナビゲーションバーと同じ高さまでにしたことがあったのですが、どのように対処したのか具体的な方法をど忘れしてしまいました
- 他にもあるでしょうか。

**Comment by cmatsuo** [comment]
+1 to getting rid of "Done" button from Navigation bar idea.

**Comment by yuji** [comment]
ナビゲーションバーをもう少し大きくして、判定エリアをナビゲーションバー内に抑える。というのはどうか

**Comment by yuji** [comment]
完了の存在も含めて将来的に見直す。
